name: Redeploy on Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
      
    - name: Check for changes in applemusic or spotify folders
      run: |
        if [[ $(git status --porcelain --branch | grep " M " | grep "applemusic" || true) || $(git status --porcelain --branch | grep " M " | grep "spotify" || true) ]]; then
          echo "Changes detected in applemusic or spotify folders. Triggering redeployment."
          exit 0
        else
          echo "No changes detected in applemusic or spotify folders. Skipping redeployment."
          exit 1
        fi
      
    - name: Use your build and deploy steps here

    - uses: actions/upload-artifact@v4
      with:
        name: deploy-artifact
