name: Redeploy Site

on:
  push:
    paths:
      - 'applemusic/**'
      - 'spotify/**'

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Jekyll
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Build site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
